import PhysicalObject
import VisualWorld
import ObjectFeature as OF
import Utterance as UT

COL_A_A_TL = PhysicalObject.PhysicalObject("guitar", [OF.ObjectFeature("brown", "color")], "TL")
COL_A_B_TL = PhysicalObject.PhysicalObject("umbrella", [OF.ObjectFeature("blue", "color")], "TL")
COL_A_C_TL = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("black", "color")], "TL")
COL_A_D_TL = PhysicalObject.PhysicalObject("watch", [OF.ObjectFeature("orange", "color")], "TL")
COL_B_A_TL = PhysicalObject.PhysicalObject("guitar", [OF.ObjectFeature("brown", "color")], "TL")
COL_B_B_TL = PhysicalObject.PhysicalObject("umbrella", [OF.ObjectFeature("blue", "color")], "TL")
COL_B_C_TL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("blue", "color")], "TL")
COL_B_D_TL = PhysicalObject.PhysicalObject("watch", [OF.ObjectFeature("red", "color")], "TL")
COL_C_A_TL = PhysicalObject.PhysicalObject("butterfly", [OF.ObjectFeature("red", "color")], "TL")
COL_C_B_TL = PhysicalObject.PhysicalObject("umbrella", [OF.ObjectFeature("blue", "color")], "TL")
COL_C_C_TL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("blue", "color")], "TL")
COL_C_D_TL = PhysicalObject.PhysicalObject("watch", [OF.ObjectFeature("red", "color")], "TL")
COL_D_A_TL = PhysicalObject.PhysicalObject("guitar", [OF.ObjectFeature("brown", "color")], "TL")
COL_D_B_TL = PhysicalObject.PhysicalObject("umbrella", [OF.ObjectFeature("blue", "color")], "TL")
COL_D_C_TL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("blue", "color")], "TL")
COL_D_D_TL = PhysicalObject.PhysicalObject("watch", [OF.ObjectFeature("red", "color")], "TL")
CAT_A_A_TL = PhysicalObject.PhysicalObject("bed", [], "TL")
CAT_A_B_TL = PhysicalObject.PhysicalObject("violin", [], "TL")
CAT_A_C_TL = PhysicalObject.PhysicalObject("bulb", [], "TL")
CAT_A_D_TL = PhysicalObject.PhysicalObject("flower", [OF.ObjectFeature("buttercup", "category")], "TL")
CAT_B_A_TL = PhysicalObject.PhysicalObject("bed", [], "TL")
CAT_B_B_TL = PhysicalObject.PhysicalObject("violin", [], "TL")
CAT_B_C_TL = PhysicalObject.PhysicalObject("shoes", [OF.ObjectFeature("highheel", "category")], "TL")
CAT_B_D_TL = PhysicalObject.PhysicalObject("flower", [OF.ObjectFeature("carnation", "category")], "TL")
CAT_C_A_TL = PhysicalObject.PhysicalObject("dog", [OF.ObjectFeature("bulldog", "category")], "TL")
CAT_C_B_TL = PhysicalObject.PhysicalObject("violin", [], "TL")
CAT_C_C_TL = PhysicalObject.PhysicalObject("shoes", [OF.ObjectFeature("highheel", "category")], "TL")
CAT_C_D_TL = PhysicalObject.PhysicalObject("flower", [OF.ObjectFeature("carnation", "category")], "TL")
CAT_D_A_TL = PhysicalObject.PhysicalObject("bed", [], "TL")
CAT_D_B_TL = PhysicalObject.PhysicalObject("violin", [], "TL")
CAT_D_C_TL = PhysicalObject.PhysicalObject("shoes", [OF.ObjectFeature("highheel", "category")], "TL")
CAT_D_D_TL = PhysicalObject.PhysicalObject("flower", [OF.ObjectFeature("carnation", "category")], "TL")
SIZE_A_A_TL = PhysicalObject.PhysicalObject("bucket", [], "TL")
SIZE_A_B_TL = PhysicalObject.PhysicalObject("drum", [], "TL")
SIZE_A_C_TL = PhysicalObject.PhysicalObject("umbrella", [], "TL")
SIZE_A_D_TL = PhysicalObject.PhysicalObject("radio", [OF.ObjectFeature("small", "size")], "TL")
SIZE_B_A_TL = PhysicalObject.PhysicalObject("bucket", [], "TL")
SIZE_B_B_TL = PhysicalObject.PhysicalObject("drum", [], "TL")
SIZE_B_C_TL = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("large", "size")], "TL")
SIZE_B_D_TL = PhysicalObject.PhysicalObject("radio", [OF.ObjectFeature("large", "size")], "TL")
SIZE_C_A_TL = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("large", "size")], "TL")
SIZE_C_B_TL = PhysicalObject.PhysicalObject("drum", [], "TL")
SIZE_C_C_TL = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("large", "size")], "TL")
SIZE_C_D_TL = PhysicalObject.PhysicalObject("radio", [OF.ObjectFeature("large", "size")], "TL")
SIZE_D_A_TL = PhysicalObject.PhysicalObject("bucket", [], "TL")
SIZE_D_B_TL = PhysicalObject.PhysicalObject("drum", [], "TL")
SIZE_D_C_TL = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("large", "size")], "TL")
SIZE_D_D_TL = PhysicalObject.PhysicalObject("radio", [OF.ObjectFeature("large", "size")], "TL")
COL_A_A_TR = PhysicalObject.PhysicalObject("butterfly", [OF.ObjectFeature("blue", "color")], "TR")
COL_A_B_TR = PhysicalObject.PhysicalObject("pot", [OF.ObjectFeature("brown", "color")], "TR")
COL_A_C_TR = PhysicalObject.PhysicalObject("hat", [OF.ObjectFeature("brown", "color")], "TR")
COL_A_D_TR = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("grey", "color")], "TR")
COL_B_A_TR = PhysicalObject.PhysicalObject("butterfly", [OF.ObjectFeature("orange", "color")], "TR")
COL_B_B_TR = PhysicalObject.PhysicalObject("pot", [OF.ObjectFeature("brown", "color")], "TR")
COL_B_C_TR = PhysicalObject.PhysicalObject("hat", [OF.ObjectFeature("brown", "color")], "TR")
COL_B_D_TR = PhysicalObject.PhysicalObject("watch", [OF.ObjectFeature("orange", "color")], "TR")
COL_C_A_TR = PhysicalObject.PhysicalObject("butterfly", [OF.ObjectFeature("orange", "color")], "TR")
COL_C_B_TR = PhysicalObject.PhysicalObject("cap", [OF.ObjectFeature("black", "color")], "TR")
COL_C_C_TR = PhysicalObject.PhysicalObject("hat", [OF.ObjectFeature("brown", "color")], "TR")
COL_C_D_TR = PhysicalObject.PhysicalObject("watch", [OF.ObjectFeature("orange", "color")], "TR")
COL_D_A_TR = PhysicalObject.PhysicalObject("butterfly", [OF.ObjectFeature("orange", "color")], "TR")
COL_D_B_TR = PhysicalObject.PhysicalObject("pot", [OF.ObjectFeature("brown", "color")], "TR")
COL_D_C_TR = PhysicalObject.PhysicalObject("hat", [OF.ObjectFeature("brown", "color")], "TR")
COL_D_D_TR = PhysicalObject.PhysicalObject("watch", [OF.ObjectFeature("orange", "color")], "TR")
CAT_A_A_TR = PhysicalObject.PhysicalObject("dog", [OF.ObjectFeature("labrador", "category")], "TR")
CAT_A_B_TR = PhysicalObject.PhysicalObject("bowl", [], "TR")
CAT_A_C_TR = PhysicalObject.PhysicalObject("bottle", [], "TR")
CAT_A_D_TR = PhysicalObject.PhysicalObject("tree", [], "TR")
CAT_B_A_TR = PhysicalObject.PhysicalObject("dog", [OF.ObjectFeature("dalmatian", "category")], "TR")
CAT_B_B_TR = PhysicalObject.PhysicalObject("bowl", [], "TR")
CAT_B_C_TR = PhysicalObject.PhysicalObject("bottle", [], "TR")
CAT_B_D_TR = PhysicalObject.PhysicalObject("flower", [OF.ObjectFeature("buttercup", "category")], "TR")
CAT_C_A_TR = PhysicalObject.PhysicalObject("dog", [OF.ObjectFeature("dalmatian", "category")], "TR")
CAT_C_B_TR = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("jeep", "category")], "TR")
CAT_C_C_TR = PhysicalObject.PhysicalObject("bottle", [], "TR")
CAT_C_D_TR = PhysicalObject.PhysicalObject("flower", [OF.ObjectFeature("buttercup", "category")], "TR")
CAT_D_A_TR = PhysicalObject.PhysicalObject("dog", [OF.ObjectFeature("dalmatian", "category")], "TR")
CAT_D_B_TR = PhysicalObject.PhysicalObject("bowl", [], "TR")
CAT_D_C_TR = PhysicalObject.PhysicalObject("bottle", [], "TR")
CAT_D_D_TR = PhysicalObject.PhysicalObject("flower", [OF.ObjectFeature("buttercup", "category")], "TR")
SIZE_A_A_TR = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("large", "size")], "TR")
SIZE_A_B_TR = PhysicalObject.PhysicalObject("chair", [], "TR")
SIZE_A_C_TR = PhysicalObject.PhysicalObject("pot", [], "TR")
SIZE_A_D_TR = PhysicalObject.PhysicalObject("alarm", [], "TR")
SIZE_B_A_TR = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("small", "size")], "TR")
SIZE_B_B_TR = PhysicalObject.PhysicalObject("chair", [], "TR")
SIZE_B_C_TR = PhysicalObject.PhysicalObject("pan", [], "TR")
SIZE_B_D_TR = PhysicalObject.PhysicalObject("radio", [OF.ObjectFeature("small", "size")], "TR")
SIZE_C_A_TR = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("small", "size")], "TR")
SIZE_C_B_TR = PhysicalObject.PhysicalObject("bird", [OF.ObjectFeature("small", "size")], "TR")
SIZE_C_C_TR = PhysicalObject.PhysicalObject("pan", [], "TR")
SIZE_C_D_TR = PhysicalObject.PhysicalObject("radio", [OF.ObjectFeature("small", "size")], "TR")
SIZE_D_A_TR = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("small", "size")], "TR")
SIZE_D_B_TR = PhysicalObject.PhysicalObject("chair", [], "TR")
SIZE_D_C_TR = PhysicalObject.PhysicalObject("pan", [], "TR")
SIZE_D_D_TR = PhysicalObject.PhysicalObject("radio", [OF.ObjectFeature("small", "size")], "TR")
COL_A_A_BR = PhysicalObject.PhysicalObject("jacket", [OF.ObjectFeature("orange", "color")], "BR")
COL_A_B_BR = PhysicalObject.PhysicalObject("cap", [OF.ObjectFeature("red", "color")], "BR")
COL_A_C_BR = PhysicalObject.PhysicalObject("bench", [OF.ObjectFeature("brown", "color")], "BR")
COL_A_D_BR = PhysicalObject.PhysicalObject("shades", [OF.ObjectFeature("black", "color")], "BR")
COL_B_A_BR = PhysicalObject.PhysicalObject("butterfly", [OF.ObjectFeature("blue", "color")], "BR")
COL_B_B_BR = PhysicalObject.PhysicalObject("cap", [OF.ObjectFeature("green", "color")], "BR")
COL_B_C_BR = PhysicalObject.PhysicalObject("bench", [OF.ObjectFeature("brown", "color")], "BR")
COL_B_D_BR = PhysicalObject.PhysicalObject("shades", [OF.ObjectFeature("black", "color")], "BR")
COL_C_A_BR = PhysicalObject.PhysicalObject("butterfly", [OF.ObjectFeature("blue", "color")], "BR")
COL_C_B_BR = PhysicalObject.PhysicalObject("cap", [OF.ObjectFeature("green", "color")], "BR")
COL_C_C_BR = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("red", "color")], "BR")
COL_C_D_BR = PhysicalObject.PhysicalObject("shades", [OF.ObjectFeature("black", "color")], "BR")
COL_D_A_BR = PhysicalObject.PhysicalObject("butterfly", [OF.ObjectFeature("blue", "color")], "BR")
COL_D_B_BR = PhysicalObject.PhysicalObject("cap", [OF.ObjectFeature("green", "color")], "BR")
COL_D_C_BR = PhysicalObject.PhysicalObject("bench", [OF.ObjectFeature("brown", "color")], "BR")
COL_D_D_BR = PhysicalObject.PhysicalObject("shades", [OF.ObjectFeature("black", "color")], "BR")
CAT_A_A_BR = PhysicalObject.PhysicalObject("boat", [], "BR")
CAT_A_B_BR = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("mercedes", "category")], "BR")
CAT_A_C_BR = PhysicalObject.PhysicalObject("fridge", [], "BR")
CAT_A_D_BR = PhysicalObject.PhysicalObject("radio", [], "BR")
CAT_B_A_BR = PhysicalObject.PhysicalObject("dog", [OF.ObjectFeature("labrador", "category")], "BR")
CAT_B_B_BR = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("porsche", "category")], "BR")
CAT_B_C_BR = PhysicalObject.PhysicalObject("fridge", [], "BR")
CAT_B_D_BR = PhysicalObject.PhysicalObject("radio", [], "BR")
CAT_C_A_BR = PhysicalObject.PhysicalObject("dog", [OF.ObjectFeature("labrador", "category")], "BR")
CAT_C_B_BR = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("porsche", "category")], "BR")
CAT_C_C_BR = PhysicalObject.PhysicalObject("shoes", [OF.ObjectFeature("male", "category")], "BR")
CAT_C_D_BR = PhysicalObject.PhysicalObject("radio", [], "BR")
CAT_D_A_BR = PhysicalObject.PhysicalObject("dog", [OF.ObjectFeature("labrador", "category")], "BR")
CAT_D_B_BR = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("porsche", "category")], "BR")
CAT_D_C_BR = PhysicalObject.PhysicalObject("fridge", [], "BR")
CAT_D_D_BR = PhysicalObject.PhysicalObject("radio", [], "BR")
SIZE_A_A_BR = PhysicalObject.PhysicalObject("rake", [], "BR")
SIZE_A_B_BR = PhysicalObject.PhysicalObject("bird", [OF.ObjectFeature("small", "size")], "BR")
SIZE_A_C_BR = PhysicalObject.PhysicalObject("cake", [], "BR")
SIZE_A_D_BR = PhysicalObject.PhysicalObject("ball", [], "BR")
SIZE_B_A_BR = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("large", "size")], "BR")
SIZE_B_B_BR = PhysicalObject.PhysicalObject("bird", [OF.ObjectFeature("large", "size")], "BR")
SIZE_B_C_BR = PhysicalObject.PhysicalObject("cake", [], "BR")
SIZE_B_D_BR = PhysicalObject.PhysicalObject("ball", [], "BR")
SIZE_C_A_BR = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("medium", "size")], "BR")
SIZE_C_B_BR = PhysicalObject.PhysicalObject("bird", [OF.ObjectFeature("large", "size")], "BR")
SIZE_C_C_BR = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("large", "size")], "BR")
SIZE_C_D_BR = PhysicalObject.PhysicalObject("ball", [], "BR")
SIZE_D_A_BR = PhysicalObject.PhysicalObject("suitcase", [OF.ObjectFeature("large", "size")], "BR")
SIZE_D_B_BR = PhysicalObject.PhysicalObject("bird", [OF.ObjectFeature("large", "size")], "BR")
SIZE_D_C_BR = PhysicalObject.PhysicalObject("cake", [], "BR")
SIZE_D_D_BR = PhysicalObject.PhysicalObject("ball", [], "BR")
COL_A_A_BL = PhysicalObject.PhysicalObject("leaf", [OF.ObjectFeature("green", "color")], "BL")
COL_A_B_BL = PhysicalObject.PhysicalObject("icecram", [OF.ObjectFeature("white", "color")], "BL")
COL_A_C_BL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("blue", "color")], "BL")
COL_A_D_BL = PhysicalObject.PhysicalObject("ladle", [OF.ObjectFeature("silver", "color")], "BL")
COL_B_A_BL = PhysicalObject.PhysicalObject("leaf", [OF.ObjectFeature("green", "color")], "BL")
COL_B_B_BL = PhysicalObject.PhysicalObject("cap", [OF.ObjectFeature("red", "color")], "BL")
COL_B_C_BL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("black", "color")], "BL")
COL_B_D_BL = PhysicalObject.PhysicalObject("ladle", [OF.ObjectFeature("silver", "color")], "BL")
COL_C_A_BL = PhysicalObject.PhysicalObject("leaf", [OF.ObjectFeature("green", "color")], "BL")
COL_C_B_BL = PhysicalObject.PhysicalObject("cap", [OF.ObjectFeature("red", "color")], "BL")
COL_C_C_BL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("black", "color")], "BL")
COL_C_D_BL = PhysicalObject.PhysicalObject("watch", [OF.ObjectFeature("blue", "color")], "BL")
COL_D_A_BL = PhysicalObject.PhysicalObject("leaf", [OF.ObjectFeature("green", "color")], "BL")
COL_D_B_BL = PhysicalObject.PhysicalObject("cap", [OF.ObjectFeature("red", "color")], "BL")
COL_D_C_BL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("black", "color")], "BL")
COL_D_D_BL = PhysicalObject.PhysicalObject("ladle", [OF.ObjectFeature("silver", "color")], "BL")
CAT_A_A_BL = PhysicalObject.PhysicalObject("umbrella", [], "BL")
CAT_A_B_BL = PhysicalObject.PhysicalObject("bottle", [], "BL")
CAT_A_C_BL = PhysicalObject.PhysicalObject("shoes", [OF.ObjectFeature("highheel", "category")], "BL")
CAT_A_D_BL = PhysicalObject.PhysicalObject("dress", [], "BL")
CAT_B_A_BL = PhysicalObject.PhysicalObject("umbrella", [], "BL")
CAT_B_B_BL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("mercedes", "category")], "BL")
CAT_B_C_BL = PhysicalObject.PhysicalObject("shoes", [OF.ObjectFeature("trainers", "category")], "BL")
CAT_B_D_BL = PhysicalObject.PhysicalObject("dress", [], "BL")
CAT_C_A_BL = PhysicalObject.PhysicalObject("umbrella", [], "BL")
CAT_C_B_BL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("mercedes", "category")], "BL")
CAT_C_C_BL = PhysicalObject.PhysicalObject("shoes", [OF.ObjectFeature("trainers", "category")], "BL")
CAT_C_D_BL = PhysicalObject.PhysicalObject("flower", [OF.ObjectFeature("tulip", "category")], "BL")
CAT_D_A_BL = PhysicalObject.PhysicalObject("umbrella", [], "BL")
CAT_D_B_BL = PhysicalObject.PhysicalObject("car", [OF.ObjectFeature("mercedes", "category")], "BL")
CAT_D_C_BL = PhysicalObject.PhysicalObject("shoes", [OF.ObjectFeature("trainers", "category")], "BL")
CAT_D_D_BL = PhysicalObject.PhysicalObject("dress", [], "BL")
SIZE_A_A_BL = PhysicalObject.PhysicalObject("candy", [], "BL")
SIZE_A_B_BL = PhysicalObject.PhysicalObject("flowers", [], "BL")
SIZE_A_C_BL = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("large", "size")], "BL")
SIZE_A_D_BL = PhysicalObject.PhysicalObject("calculator", [], "BL")
SIZE_B_A_BL = PhysicalObject.PhysicalObject("candy", [], "BL")
SIZE_B_B_BL = PhysicalObject.PhysicalObject("bird", [OF.ObjectFeature("small", "size")], "BL")
SIZE_B_C_BL = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("small", "size")], "BL")
SIZE_B_D_BL = PhysicalObject.PhysicalObject("calculator", [], "BL")
SIZE_C_A_BL = PhysicalObject.PhysicalObject("candy", [], "BL")
SIZE_C_B_BL = PhysicalObject.PhysicalObject("bird", [OF.ObjectFeature("small", "size")], "BL")
SIZE_C_C_BL = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("small", "size")], "BL")
SIZE_C_D_BL = PhysicalObject.PhysicalObject("radio", [OF.ObjectFeature("small", "size")], "BL")
SIZE_D_A_BL = PhysicalObject.PhysicalObject("candy", [], "BL")
SIZE_D_B_BL = PhysicalObject.PhysicalObject("bird", [OF.ObjectFeature("small", "size")], "BL")
SIZE_D_C_BL = PhysicalObject.PhysicalObject("sofa", [OF.ObjectFeature("small", "size")], "BL")
SIZE_D_D_BL = PhysicalObject.PhysicalObject("calculator", [], "BL")

# Build Visual Worlds
COL_A_A = VisualWorld.VisualWorld(
    [COL_A_A_TL, COL_A_A_TR, COL_A_A_BL, COL_A_A_BR])
COL_A_B = VisualWorld.VisualWorld(
    [COL_A_B_TL, COL_A_B_TR, COL_A_B_BL, COL_A_B_BR])
COL_A_C = VisualWorld.VisualWorld(
    [COL_A_C_TL, COL_A_C_TR, COL_A_C_BL, COL_A_C_BR])
COL_A_D = VisualWorld.VisualWorld(
    [COL_A_D_TL, COL_A_D_TR, COL_A_D_BL, COL_A_D_BR])
COL_B_A = VisualWorld.VisualWorld(
    [COL_B_A_TL, COL_B_A_TR, COL_B_A_BL, COL_B_A_BR])
COL_B_B = VisualWorld.VisualWorld(
    [COL_B_B_TL, COL_B_B_TR, COL_B_B_BL, COL_B_B_BR])
COL_B_C = VisualWorld.VisualWorld(
    [COL_B_C_TL, COL_B_C_TR, COL_B_C_BL, COL_B_C_BR])
COL_B_D = VisualWorld.VisualWorld(
    [COL_B_D_TL, COL_B_D_TR, COL_B_D_BL, COL_B_D_BR])
COL_C_A = VisualWorld.VisualWorld(
    [COL_C_A_TL, COL_C_A_TR, COL_C_A_BL, COL_C_A_BR])
COL_C_B = VisualWorld.VisualWorld(
    [COL_C_B_TL, COL_C_B_TR, COL_C_B_BL, COL_C_B_BR])
COL_C_C = VisualWorld.VisualWorld(
    [COL_C_C_TL, COL_C_C_TR, COL_C_C_BL, COL_C_C_BR])
COL_C_D = VisualWorld.VisualWorld(
    [COL_C_D_TL, COL_C_D_TR, COL_C_D_BL, COL_C_D_BR])
COL_D_A = VisualWorld.VisualWorld(
    [COL_D_A_TL, COL_D_A_TR, COL_D_A_BL, COL_D_A_BR])
COL_D_B = VisualWorld.VisualWorld(
    [COL_D_B_TL, COL_D_B_TR, COL_D_B_BL, COL_D_B_BR])
COL_D_C = VisualWorld.VisualWorld(
    [COL_D_C_TL, COL_D_C_TR, COL_D_C_BL, COL_D_C_BR])
COL_D_D = VisualWorld.VisualWorld(
    [COL_D_D_TL, COL_D_D_TR, COL_D_D_BL, COL_D_D_BR])
CAT_A_A = VisualWorld.VisualWorld(
    [CAT_A_A_TL, CAT_A_A_TR, CAT_A_A_BL, CAT_A_A_BR])
CAT_A_B = VisualWorld.VisualWorld(
    [CAT_A_B_TL, CAT_A_B_TR, CAT_A_B_BL, CAT_A_B_BR])
CAT_A_C = VisualWorld.VisualWorld(
    [CAT_A_C_TL, CAT_A_C_TR, CAT_A_C_BL, CAT_A_C_BR])
CAT_A_D = VisualWorld.VisualWorld(
    [CAT_A_D_TL, CAT_A_D_TR, CAT_A_D_BL, CAT_A_D_BR])
CAT_B_A = VisualWorld.VisualWorld(
    [CAT_B_A_TL, CAT_B_A_TR, CAT_B_A_BL, CAT_B_A_BR])
CAT_B_B = VisualWorld.VisualWorld(
    [CAT_B_B_TL, CAT_B_B_TR, CAT_B_B_BL, CAT_B_B_BR])
CAT_B_C = VisualWorld.VisualWorld(
    [CAT_B_C_TL, CAT_B_C_TR, CAT_B_C_BL, CAT_B_C_BR])
CAT_B_D = VisualWorld.VisualWorld(
    [CAT_B_D_TL, CAT_B_D_TR, CAT_B_D_BL, CAT_B_D_BR])
CAT_C_A = VisualWorld.VisualWorld(
    [CAT_C_A_TL, CAT_C_A_TR, CAT_C_A_BL, CAT_C_A_BR])
CAT_C_B = VisualWorld.VisualWorld(
    [CAT_C_B_TL, CAT_C_B_TR, CAT_C_B_BL, CAT_C_B_BR])
CAT_C_C = VisualWorld.VisualWorld(
    [CAT_C_C_TL, CAT_C_C_TR, CAT_C_C_BL, CAT_C_C_BR])
CAT_C_D = VisualWorld.VisualWorld(
    [CAT_C_D_TL, CAT_C_D_TR, CAT_C_D_BL, CAT_C_D_BR])
CAT_D_A = VisualWorld.VisualWorld(
    [CAT_D_A_TL, CAT_D_A_TR, CAT_D_A_BL, CAT_D_A_BR])
CAT_D_B = VisualWorld.VisualWorld(
    [CAT_D_B_TL, CAT_D_B_TR, CAT_D_B_BL, CAT_D_B_BR])
CAT_D_C = VisualWorld.VisualWorld(
    [CAT_D_C_TL, CAT_D_C_TR, CAT_D_C_BL, CAT_D_C_BR])
CAT_D_D = VisualWorld.VisualWorld(
    [CAT_D_D_TL, CAT_D_D_TR, CAT_D_D_BL, CAT_D_D_BR])
SIZE_A_A = VisualWorld.VisualWorld(
    [SIZE_A_A_TL, SIZE_A_A_TR, SIZE_A_A_BL, SIZE_A_A_BR])
SIZE_A_B = VisualWorld.VisualWorld(
    [SIZE_A_B_TL, SIZE_A_B_TR, SIZE_A_B_BL, SIZE_A_B_BR])
SIZE_A_C = VisualWorld.VisualWorld(
    [SIZE_A_C_TL, SIZE_A_C_TR, SIZE_A_C_BL, SIZE_A_C_BR])
SIZE_A_D = VisualWorld.VisualWorld(
    [SIZE_A_D_TL, SIZE_A_D_TR, SIZE_A_D_BL, SIZE_A_D_BR])
SIZE_B_A = VisualWorld.VisualWorld(
    [SIZE_B_A_TL, SIZE_B_A_TR, SIZE_B_A_BL, SIZE_B_A_BR])
SIZE_B_B = VisualWorld.VisualWorld(
    [SIZE_B_B_TL, SIZE_B_B_TR, SIZE_B_B_BL, SIZE_B_B_BR])
SIZE_B_C = VisualWorld.VisualWorld(
    [SIZE_B_C_TL, SIZE_B_C_TR, SIZE_B_C_BL, SIZE_B_C_BR])
SIZE_B_D = VisualWorld.VisualWorld(
    [SIZE_B_D_TL, SIZE_B_D_TR, SIZE_B_D_BL, SIZE_B_D_BR])
SIZE_C_A = VisualWorld.VisualWorld(
    [SIZE_C_A_TL, SIZE_C_A_TR, SIZE_C_A_BL, SIZE_C_A_BR])
SIZE_C_B = VisualWorld.VisualWorld(
    [SIZE_C_B_TL, SIZE_C_B_TR, SIZE_C_B_BL, SIZE_C_B_BR])
SIZE_C_C = VisualWorld.VisualWorld(
    [SIZE_C_C_TL, SIZE_C_C_TR, SIZE_C_C_BL, SIZE_C_C_BR])
SIZE_C_D = VisualWorld.VisualWorld(
    [SIZE_C_D_TL, SIZE_C_D_TR, SIZE_C_D_BL, SIZE_C_D_BR])
SIZE_D_A = VisualWorld.VisualWorld(
    [SIZE_D_A_TL, SIZE_D_A_TR, SIZE_D_A_BL, SIZE_D_A_BR])
SIZE_D_B = VisualWorld.VisualWorld(
    [SIZE_D_B_TL, SIZE_D_B_TR, SIZE_D_B_BL, SIZE_D_B_BR])
SIZE_D_C = VisualWorld.VisualWorld(
    [SIZE_D_C_TL, SIZE_D_C_TR, SIZE_D_C_BL, SIZE_D_C_BR])
SIZE_D_D = VisualWorld.VisualWorld(
    [SIZE_D_D_TL, SIZE_D_D_TR, SIZE_D_D_BL, SIZE_D_D_BR])

# load utterances
COL_A_A_Utterance = UT.Utterance('butterfly')
COL_B_A_Utterance = UT.Utterance('butterfly', [OF.ObjectFeature('orange',"color")])
COL_C_A_Utterance = UT.Utterance('butterfly', [OF.ObjectFeature('orange',"color")])
COL_D_A_Utterance = UT.Utterance('butterfly')
COL_A_B_Utterance = UT.Utterance('cap')
COL_B_B_Utterance = UT.Utterance('cap', [OF.ObjectFeature('green', "color")])
COL_C_B_Utterance = UT.Utterance('cap', [OF.ObjectFeature('green', "color")])
COL_D_B_Utterance = UT.Utterance('cap')
COL_A_C_Utterance = UT.Utterance('car')
COL_B_C_Utterance = UT.Utterance('car', [OF.ObjectFeature('black', "color")])
COL_C_C_Utterance = UT.Utterance('car', [OF.ObjectFeature('black', "color")])
COL_D_C_Utterance = UT.Utterance('car')
COL_A_D_Utterance = UT.Utterance('watch')
COL_B_D_Utterance = UT.Utterance('watch', [OF.ObjectFeature('red', "color")])
COL_C_D_Utterance = UT.Utterance('watch', [OF.ObjectFeature('red', "color")])
COL_D_D_Utterance = UT.Utterance('watch')
SIZE_A_A_Utterance = UT.Utterance('suitcase')
SIZE_B_A_Utterance = UT.Utterance('suitcase', [OF.ObjectFeature('small', "size")])
SIZE_C_A_Utterance = UT.Utterance('suitcase', [OF.ObjectFeature('small', "size")])
SIZE_D_A_Utterance = UT.Utterance('suitcase')
SIZE_A_B_Utterance = UT.Utterance('bird')
SIZE_B_B_Utterance = UT.Utterance('bird', [OF.ObjectFeature('large', "size")])
SIZE_C_B_Utterance = UT.Utterance('bird', [OF.ObjectFeature('large', "size")])
SIZE_D_B_Utterance = UT.Utterance('bird')
SIZE_A_C_Utterance = UT.Utterance('sofa')
SIZE_B_C_Utterance = UT.Utterance('sofa', [OF.ObjectFeature('small', "size")])
SIZE_C_C_Utterance = UT.Utterance('sofa', [OF.ObjectFeature('small', "size")])
SIZE_D_C_Utterance = UT.Utterance('sofa')
SIZE_A_D_Utterance = UT.Utterance('radio')
SIZE_B_D_Utterance = UT.Utterance('radio', [OF.ObjectFeature('large', "size")])
SIZE_C_D_Utterance = UT.Utterance('radio', [OF.ObjectFeature('large', "size")])
SIZE_D_D_Utterance = UT.Utterance('radio')
CAT_A_A_Utterance = UT.Utterance('dog')
CAT_B_A_Utterance = UT.Utterance('dog', [OF.ObjectFeature('dalmatian', "category")])
CAT_C_A_Utterance = UT.Utterance('dog', [OF.ObjectFeature('dalmatian', "category")])
CAT_D_A_Utterance = UT.Utterance('dog')
CAT_A_B_Utterance = UT.Utterance('car')
CAT_B_B_Utterance = UT.Utterance('car', [OF.ObjectFeature('porsche', "category")])
CAT_C_B_Utterance = UT.Utterance('car', [OF.ObjectFeature('porsche', "category")])
CAT_D_B_Utterance = UT.Utterance('car')
CAT_A_C_Utterance = UT.Utterance('shoes')
CAT_B_C_Utterance = UT.Utterance('shoes', [OF.ObjectFeature('trainers', "category")])
CAT_C_C_Utterance = UT.Utterance('shoes', [OF.ObjectFeature('trainers', "category")])
CAT_D_C_Utterance = UT.Utterance('shoes')
CAT_A_D_Utterance = UT.Utterance('flower')
CAT_B_D_Utterance = UT.Utterance('flower', [OF.ObjectFeature('carnation', "category")])
CAT_C_D_Utterance = UT.Utterance('flower', [OF.ObjectFeature('carnation', "category")])
CAT_D_D_Utterance = UT.Utterance('flower')
